### ISSUE TITLE
Cannot install the app at all

### ISSUE THREAD

**Issue by KennethLavrsen** [mtudor/HomeySqueezebox#14]
Hi
I have a newly purchased and freshly updated Homey.
I have installed the HomeySqueezebox app and try to install a Squeezebox

I never get anywhere. When you try to install the Squeezebox device a windows comes up asking me to follow instructions and a rotating icon keeps spinning for a minute or so and then it all crashes with the message "invalid_session". I never get to the point where I can click or enter any information. I cannot see what I possibly do wrong. I have a Logitech Media Server on my Network and it works fine with multiple players and controls.

**Comment by mtudor** [comment]
Hi Kenneth,

I've just done a complete reinstall and the app works for me (Homey Firmware Version: 1.5.8).  What version are you on?  Did you add the address of your LMS in the settings page before attempting to add devices?

I know that there is still a lot of functionality to add to this app, and I do still plan to do this, time permitting, but it should fill basic needs.  Let's see if we can get you up and running...

Mark.

**Comment by KennethLavrsen** [comment]
Now I see the problem.

Remember that I am a new Homey user. I assumed that you first install the App, then add the device and then when installed you would add the server to the settings of the device. because that is how the other devices I installed behaved. Now I see that in the Homey app - in the Settings of Homey - there is a new entry at the bottom of the left menu, called Squeezebox. When I read your installation description then I can see that this is what you write, but it is not very obvious to a newbie that installing the app adds a new setting menu entry in the Homey app. You may want to add one line of text in the installation instruction that a new menu entry is added. Currently the text says

"Configure the App Install the app and then add the correct server address and port in Settings > Squeezebox. Usually, leaving the Server Port at the default 9000 is fine. "

I would spell it out.
1. Install the App from the App Store

2. Once installed a new "Squeezebox" item is added to the Settings in the Homey App

3. Open the Squeezebox setting and enter the address and port number of the Logitech Media Server
The Server Address should be specified as the address of the Logitech Media Server, including the "http://" part. A name or ip address can be used:

Server Address: http://squeezebox.mydomain.co.uk
Server Address: http://squeezebox
Server Address: http://192.168.0.1

Usually, leaving the Server Port at the default 9000 is fine.  It may be a different port, e.g. Synology uses port 9002.

From there your installation instructions are fine

I had to change my port to 9002. It seems that is the default for Synology installed Logitect Media Servers.

Once I had tried with the wrong port I could not install anything even when corrected and App restart. Then I removed the app, reinstalled it, and then it worked.

Now my next question comes up... what now?

I have no clue how to operate the App once installed. I have tried different things with Alexa but I could not guess anything right related to this App. It really needs just a little but of additional documentation

**Comment by mtudor** [comment]
Hi Kenneth,

Glad you've managed to get things working.  Please appreciate that I am an independent developer, not a paid member of Athom.  The HomeySqueezebox app was developed in my free time, in addition to a demanding full time job, because I wanted something to allow Homey to control my own Squeezeboxes and I thought it would be nice to share.  I know the app requires more work (automatic discovery of the LMS for a start, along with integration with Homey Music) and this is something I very much want to do, in time.

Thank you for the suggested documentation changes - I will make these now, and will try to also add an outline of the functionality the app adds.  For your immediate needs, however, you need to:

1. Use the add device functionality of Homey (now you've configured the app) to add your individual squeezeboxes.

2. Go to the FLOW section of homey and you can then drag these devices into the third column to perform some basic actions such as play / pause / volume / play playlist.  More functionality is yet to be developed.

Assuming you are happy to update your rating on the store once you have the app working, please do rate based on the functionality that is there rather than what is not.

Best wishes,

Mark.

**Comment by mtudor** [comment]
I've updated the documentation which should hopefully help people for now, until we can get the bits that are slightly less user-friendly sorted out.
